# Generated by Django 5.2.13 on 2026-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('best_size', models.IntegerField(default=0)),
                ('hours_played', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
